//sratos
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication22;

/**
 *
 * @author WorkSpace//testing
 */
public class NewJFrame extends javax.swing.JFrame {
//bubolbo
    double firstnum;
    double secondnum;
    double result;
    
    Calculator calc = new Calculator();
    
    String operation;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        jtextfield1 = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        point = new javax.swing.JButton();
        power = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        riza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        percent = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        log = new javax.swing.JButton();
        ln = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        ntekakaintunamh = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 30));

        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 50, 30));

        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 50, 30));

        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 50, 30));

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 50, 30));

        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 50, 30));

        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 50, 30));

        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 30));

        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 50, 30));

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 50, 30));

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 50, 20));

        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        getContentPane().add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 50, 30));

        jtextfield1.setEditable(false);
        jtextfield1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jtextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 190, 30));

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 60, 70));

        minus.setLabel("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 60, 20));

        point.setText(".");
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed1(evt);
            }
        });
        getContentPane().add(point, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 50, 30));

        power.setText("x^n");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });
        getContentPane().add(power, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 60, 20));

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 60, 20));

        riza.setText("sqrt");
        riza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rizaActionPerformed(evt);
            }
        });
        getContentPane().add(riza, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Calculator manmu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, 20));

        back.setText("<--");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, -1));

        percent.setText("%");
        percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentActionPerformed(evt);
            }
        });
        getContentPane().add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 60, 20));

        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        getContentPane().add(sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 60, 20));

        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        getContentPane().add(cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 60, 20));

        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        getContentPane().add(tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, 20));

        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, 20));

        ln.setText("ln");
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 59, 20));

        exp.setText("exp");
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });
        getContentPane().add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 60, 20));

        ntekakaintunamh.setText("10^x");
        ntekakaintunamh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntekakaintunamhActionPerformed(evt);
            }
        });
        getContentPane().add(ntekakaintunamh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 62, 20));

        pi.setText("π");
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });
        getContentPane().add(pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, -1));

        multi.setText("*");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        getContentPane().add(multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 61, 20));

        jMenu1.setText("ΠΡΟΒΟΛΗ");

        jMenuItem1.setText("ΤΥΠΙΚΗ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("ΕΠΙΣΤΗΜΟΝΙΚΗ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        String textin = jtextfield1.getText()+one.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        String textin = jtextfield1.getText()+two.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        String textin = jtextfield1.getText()+three.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        String textin = jtextfield1.getText()+four.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        String textin = jtextfield1.getText()+five.getText();
				jtextfield1.setText(textin);        // TODO add your handling code here:
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        String textin = jtextfield1.getText()+six.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        String textin = jtextfield1.getText()+seven.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        String textin = jtextfield1.getText()+eight.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        String textin = jtextfield1.getText()+nine.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        String textin = jtextfield1.getText()+zero.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_zeroActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        String answer ;
	switch (operation)
	{
	case "+" :
                secondnum=Double.parseDouble(jtextfield1.getText());
		result= calc.Add(firstnum, secondnum);
		answer = Double.toString(result) ;
		jtextfield1.setText(answer);
 		break;
        case "-" :
                secondnum=Double.parseDouble(jtextfield1.getText());
                result= calc.Sub(firstnum, secondnum);
		answer = Double.toString(result) ;                
		jtextfield1.setText(answer);					
		break;
         case "*" :    
                secondnum=Double.parseDouble(jtextfield1.getText());
                result= calc.Mult(firstnum, secondnum);
		answer = Double.toString(result) ;
		jtextfield1.setText(answer);					
		break;
         case "/" :
                secondnum=Double.parseDouble(jtextfield1.getText());
                result= calc.Div(firstnum, secondnum);
		answer = Double.toString(result) ;                
		jtextfield1.setText(answer);					
		break;
         case "^" :    
                secondnum=Double.parseDouble(jtextfield1.getText());
                result= calc.Pow(firstnum,secondnum)   ;
		answer = Double.toString(result) ;
		jtextfield1.setText(answer);					
		break; 
         case "sqrt" :
                result= calc.Sqrt(firstnum) ;
                answer = Double.toString (result) ;
                jtextfield1.setText(answer);
                break;
         case "%" :
                secondnum=Double.parseDouble(jtextfield1.getText());
                result= (firstnum * secondnum)/100;
		answer = Double.toString(result) ;                
		jtextfield1.setText(answer);					
		break;   
         case "pi" :
                result=calc.Pi();
                answer = Double.toString(result);
                jtextfield1.setText(answer);
                break;
         case "exp" :
                result=calc.Exp(firstnum);
                answer = Double.toString(result) ;                
		jtextfield1.setText(answer);
                break;
        }
    }//GEN-LAST:event_equalActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
      firstnum = Double.parseDouble(jtextfield1.getText());
      jtextfield1.setText("");
      operation = "+";
    }//GEN-LAST:event_plusActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        jtextfield1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
	jtextfield1.setText("");
	operation = "-";
    }//GEN-LAST:event_minusActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed

        firstnum = Double.parseDouble(jtextfield1.getText());
	jtextfield1.setText("");
	operation = "^";      
    }//GEN-LAST:event_powerActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        jtextfield1.setText("");
        operation = "/";
    }//GEN-LAST:event_divideActionPerformed

    private void rizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rizaActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        result= Math.sqrt(firstnum);
        jtextfield1.setText(Double.toString(result));
    }//GEN-LAST:event_rizaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        String text=jtextfield1.getText();
        int len=text.length();
        
        text=text.substring(0,len-1);
        jtextfield1.setText(text);     
    }//GEN-LAST:event_backActionPerformed

    private void percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        jtextfield1.setText("");
        operation = "%";
    }//GEN-LAST:event_percentActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        result= Math.sin(Math.toRadians(firstnum));
        jtextfield1.setText(Double.toString(result));
    }//GEN-LAST:event_sinActionPerformed
//cos function 
    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        result= Math.cos(Math.toRadians(firstnum));
        jtextfield1.setText(Double.toString(result));
    }//GEN-LAST:event_cosActionPerformed

    private void pointActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed1
        String textin = jtextfield1.getText()+point.getText();
				jtextfield1.setText(textin);
    }//GEN-LAST:event_pointActionPerformed1

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        result= Math.tan(Math.toRadians(firstnum));
        jtextfield1.setText(Double.toString(result));
    }//GEN-LAST:event_tanActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        result= Math.log10(firstnum);
        jtextfield1.setText(Double.toString(result));
    }//GEN-LAST:event_logActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        result= Math.log(firstnum);
        jtextfield1.setText(Double.toString(result));
    }//GEN-LAST:event_lnActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        jtextfield1.setText("");
        operation = "exp";
    }//GEN-LAST:event_expActionPerformed

    private void ntekakaintunamhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntekakaintunamhActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        result= Math.pow(10, firstnum);
        jtextfield1.setText(Double.toString(result));
    }//GEN-LAST:event_ntekakaintunamhActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        operation = "pi";
    }//GEN-LAST:event_piActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        firstnum = Double.parseDouble(jtextfield1.getText());
        jtextfield1.setText("");
        operation = "*";
    }//GEN-LAST:event_multiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        riza.setVisible(false);
        tan.setVisible(false);
        log.setVisible(false);
        ln.setVisible(false);
        sin.setVisible(false);
        exp.setVisible(false);
        cos.setVisible(false);
        ntekakaintunamh.setVisible(false);
        percent.setVisible(false);
        power.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        riza.setVisible(true);
        tan.setVisible(true);
        log.setVisible(true);
        ln.setVisible(true);
        sin.setVisible(true);
        exp.setVisible(true);
        cos.setVisible(true);
        ntekakaintunamh.setVisible(true);
        percent.setVisible(true);
        power.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton cos;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton exp;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jtextfield1;
    private javax.swing.JButton ln;
    private javax.swing.JButton log;
    private javax.swing.JButton minus;
    private javax.swing.JButton multi;
    private javax.swing.JButton nine;
    private javax.swing.JButton ntekakaintunamh;
    private javax.swing.JButton one;
    private javax.swing.JButton percent;
    private javax.swing.JButton pi;
    private javax.swing.JButton plus;
    private javax.swing.JButton point;
    private javax.swing.JButton power;
    private javax.swing.JButton riza;
    private javax.swing.JButton seven;
    private javax.swing.JButton sin;
    private javax.swing.JButton six;
    private javax.swing.JButton tan;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
